config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  get 'ngos/add_students'
  get 'ngos/sign_in'
  post 'ngos/verify_sign_in'
  get 'ngos/sign_out'

  resources :ngos

  root 'ngos#index'

end

app/models/ngo.rb
class Ngo < ActiveRecord::Base

	has_secure_password

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ngos_controller.rb
class NgosController < ApplicationController
  before_action :set_ngo, only: [:show, :edit, :update, :destroy]
  skip_before_filter
  # GET /ngos
  # GET /ngos.json
  def index
    @ngos = Ngo.all
    # reset_session
  end

  # GET /ngos/1
  # GET /ngos/1.json
  def show
  end

  # GET /ngos/new
  def new
    @ngo = Ngo.new
  end

  # GET /ngos/1/edit
  def edit
  end

  # POST /ngos
  # POST /ngos.json
  def create
    @ngo = Ngo.new(ngo_params)

    respond_to do |format|
      if @ngo.save
        format.html { redirect_to @ngo, notice: 'Ngo was successfully created.' }
        format.json { render :show, status: :created, location: @ngo }
      else
        format.html { render :new }
        format.json { render json: @ngo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ngos/1
  # PATCH/PUT /ngos/1.json
  def update
    respond_to do |format|
      if @ngo.update(ngo_params)
        format.html { redirect_to @ngo, notice: 'Ngo was successfully updated.' }
        format.json { render :show, status: :ok, location: @ngo }
      else
        format.html { render :edit }
        format.json { render json: @ngo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ngos/1
  # DELETE /ngos/1.json
  def destroy
    @ngo.destroy
    respond_to do |format|
      format.html { redirect_to ngos_url, notice: 'Ngo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_students
    if session[:ngo_id].present?
      render ngos_add_students_path
    else
      redirect_to '/', alert: "Please login with NGO name and password to access this page."
    end
  end

  def verify_sign_in

    @ngo = Ngo.find_by(name: params[:name])
    
    if @ngo.present?
      if @ngo.authenticate(params[:password])
        session[:ngo_id] = @ngo.id
        # binding.pry
        redirect_to new_user_registration_path, alert: "Signed in successfully."
      else
        redirect_to :back, alert: "Password entered is wrong. Please try again."
      end
    else
      redirect_to :back, alert: "NGO doesn't exist."
    end

  end

  def sign_out
    session.delete("ngo_id")
    redirect_to '/', alert: "Signed out successfully."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ngo
      @ngo = Ngo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ngo_params
      params.require(:ngo).permit(:name, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ngos_helper.rb
module NgosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoSessionAuth428</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <% if session[:ngo_id].present? %>
  	<%= link_to "Sign Out - NGO", ngos_sign_out_path %>
  <% else %>
  	<%= link_to "Sign In - NGO", ngos_sign_in_path %>
  <% end %>
  <% if !user_signed_in? %>
  	<%= link_to "Login - Devise", new_user_session_path %>
  	<%= link_to "Signup - Devise", new_user_registration_path %>
  <% else %>
    <%= link_to "Edit Account - Devise", edit_user_registration_path %>
  	<%= link_to "Logout - Devise", destroy_user_session_path, method: :delete %>
  <% end %>
  <%= link_to "Add Student", ngos_add_students_path %>
  <%= link_to "All NGOs", ngos_path %>
  <br/><br/>

</head>
<body>

<p id="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/ngos/_form.html.erb
<%= form_for(@ngo) do |f| %>
  <% if @ngo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ngo.errors.count, "error") %> prohibited this ngo from being saved:</h2>

      <ul>
      <% @ngo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password, {type: "password"} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ngos/edit.html.erb
<h1>Editing Ngo</h1>

<%= render 'form' %>

<%= link_to 'Show', @ngo %> |
<%= link_to 'Back', ngos_path %>

app/views/ngos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ngos</h1>
<%#= binding.pry %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ngos.each do |ngo| %>
      <tr>
        <td><%= ngo.name %></td>
        <td><%= ngo.password %></td>
        <td><%= link_to 'Show', ngo %></td>
        <td><%= link_to 'Edit', edit_ngo_path(ngo) %></td>
        <td><%= link_to 'Destroy', ngo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ngo', new_ngo_path %>

app/views/ngos/new.html.erb
<h1>New Ngo</h1>

<%= render 'form' %>

<%= link_to 'Back', ngos_path %>

app/views/ngos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ngo.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @ngo.password %>
</p>

<%= link_to 'Edit', edit_ngo_path(@ngo) %> |
<%= link_to 'Back', ngos_path %>

app/views/ngos/sign_in.html.erb
<%= form_tag({controller: "ngos", action: "verify_sign_in"}, method: "post") %>

<label>Name: </label>
<%= text_field_tag :name %>

<br/><br/>

<label>Password: </label>
<%= text_field_tag :password, "", {type: "password"} %>

<br/><br/>

<%= button_tag :Submit %>